name: publish

on:
  push:
    branches: [ add_gh_action ]
  pull_request:
    branches: [ main ]

jobs:
  build-rfc:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install kramdown-rfc
        run: gem install kramdown-rfc
      - name: Install xml2rfc
        run: pip install xml2rfc
      - name: Convert to rfc xml
        run: kramdown-rfc draft-ietf-identity-chaining.md > draft-ietf-identity-chaining.xml
      - name: Render HTML
        run: xml2rfc draft-ietf-identity-chaining.xml --html
      - name: Render Text
        run: xml2rfc draft-ietf-identity-chaining.xml --text
      - name: Deploy to gh-pages
        uses: actions/upload-artifact@v2
        with:
          name: draft-ietf-identity-chaining
          path: |
            draft-ietf-identity-chaining.html
            draft-ietf-identity-chaining.xml
