name: publish

on:
  push:
    branches: [ add_gh_action ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install kramdown-rfc
        run: gem install kramdown-rfc
      - name: Install xml2rfc
        run: pip install xml2rfc
